# fly.toml app configuration file generated for intellibus-api-vision-1 on 2025-10-19T13:43:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'intellibus-api-vision-1'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1  # Keep 1 machine always running to avoid cold starts
  processes = ['app']

[[http_service.checks]]
  grace_period = "120s"  # 2 minutes for model loading
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/docs"

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
